name: APIM - Run Extractor
permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      SOURCE_ENVIRONMENT_NAME:
        description: 'Choose the source environment name'
        required: true
        type: choice
        default: dev
        options: 
          - dev
          - test
      CONFIGURATION_YAML_PATH:
        description: 'Choose whether to extract all Apis or extract apis listed an extraction configuration file'     
        required: true
        type: choice
        options:
        - Extract All APIs
        - Extract Specific API
      API_SPECIFICATION_FORMAT:
        description: 'API Specification Format'     
        required: true
        type: choice
        options:
        - OpenAPIV3Yaml 
        - OpenAPIV3Json
        - OpenAPIV2Yaml
        - OpenAPIV2Json

env:
  apiops_release_version: v6.0.1.10

jobs:
         
  create-pull-request:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: add new files
        run: |
          echo "Current Time: $(date +'%H:%M:%S')" >> something.txt
          git add .

      - name: Skip if no changes
        id: diffcheck
        run: |
          if git diff --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
 
      - name: Stop early if nothing to commit
        if: steps.diffcheck.outputs.changed == 'false'
        run: |
          echo "No file changes detected. Exiting."
          exit 1
      

      - name: Authenticate gh CLI
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          # git add .
          # git commit -m "chore: generate content and update apimartifacts"
          # git push
      
      - name: Create working branch (when on master)
        if: ${{ github.ref_name }} == 'master'
        id: create_branch
        run: |
          NEW_BRANCH="automated/apim-extractor-update"
          git checkout -b "$NEW_BRANCH"
          echo "new_branch=$NEW_BRANCH" >> "$GITHUB_OUTPUT"
 
      - name: Commit changes (when on master)
        if: ${{ github.ref_name }} == 'master'
        run: |
          git add .
          git commit -m "chore: generate content and update apimartifacts"
          git push origin "${{ steps.create_branch.outputs.new_branch }}"
          echo "hi"
      
      - name: Commit changes (when not on master)
        if: ${{ github.ref_name }} != 'master'
        run: |
          git add .
          git commit -m "chore: generate content and update apimartifacts"
          git push origin "${{ github.ref_name }}"
      - name: Determine PR head branch
        id: headref
        run: |
          if [ "${{ github.ref_name }}" = "master" ]; then
            echo "head=${{ steps.create_branch.outputs.new_branch }}" >> "$GITHUB_OUTPUT"
          else
            echo "head=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          fi
      # Open a pull request using the GitHub CLI
      - name: Open pull request using gh CLI
        run: |
          gh pr create \
            --title "chore: update extract from apim instance ${{ env.API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH }}" \
            --body "This PR is auto-generated by GitHub Actions workflow."
             --base master \
             --head "${{ steps.headref.outputs.head }}"
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apim/apimartifacts  # Path to your artifacts folder
