name: Context_Learning
on: push
jobs:
    Printing_context:
        runs-on: ubuntu-latest
        steps: 
            - name: Json_github
              run: echo "${{toJson(github)}}"
            - name: checking_out
              uses: actions/checkout@v4
            - name: echo_things
              run: echo "${{github.ref_name}}"
