name: environment
on: 
    workflow_dispatch:
      inputs:
        name:
            description: 'enter the name'
            required: true
            default: 'Ammu'
            type: string
jobs:
    printing_the_variable:
        runs-on: ubuntu-latest
        environment: Testing # it will only work when you already configured the environment
        steps: 
            - name: step1
              run: |
                echo ${{vars.NAME}}
                echo ${{inputs.name}}
            - name: step2
              run: echo "Step 2 executed"






