name: Read Check Status

on:
  push:
    branches:
      - master

jobs:
  check-status:
    runs-on: ubuntu-latest
    permissions:
      checks: read  # Permission to read check status

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get status of check runs
        run: echo ${{toJson(github.event)}}