name: Read Check Status

on:
  push:
    branches:
      - master

jobs:
  check-status:
    runs-on: ubuntu-latest
    permissions:
      checks: read  # Permission to read check status

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get status of check runs
        run: |
          # Fetch the check status of the latest commit
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/check-runs
